### PR TITLE
Update SteamBulkKeyActivator.ahk

### PR DESCRIPTION
**Pull request by VijayS1**
Updated it with some keyboard shortcuts, new positions of some buttons. 
New routine to find buttons on the form. Basically making it work with steam today. 
TO DO: Test if it now works with all test cases.
I've tested with :
Duplicate key: works 
too many attempts : works
New product : Not tested yet
invalid key: works

### CODE REVIEW

**Comment by colingg** [comment]
Ideally I'd love to merge both #8 and #6.
I don't have time the upcoming days, is either one of you prepared to check both PR's out ?

**Comment by VijayS1** [comment]
any link to documentation on how to merge the two patches? I don't know how to go about it on github. 

#6 I changed the way clicking on button works, tried to use the keyboard more often. 
#8 uses the old way to click buttons and makes changes to logging and parsing of content

**Comment by makedir** [comment]
@colingg can you please make a change to the fork, that it works for other resolutions than 1920x1080 and also if Windows window scale is other than 100%, because then your script misclicks and doesn't hit the buttons anymore.

**Comment by VijayS1** [comment]
What about the keyboard version? Where it uses tabs to click?

**Pull request merged**
